### ISSUE TITLE
你好 

### ISSUE THREAD

**Issue by zhaokailin** [Famine-Life/Lbook#1]
我下载 你的项目后 导入eclipse报错 可以给我指导一下吗

**Comment by Famine-Life** [comment]
报错信息贴出来



---原始邮件---
发件人: "zhaokailin"<notifications@github.com&gt;
发送时间: 2019年11月2日(星期六) 中午11:50
收件人: "Famine-Life/Lbook"<Lbook@noreply.github.com&gt;;
抄送: "Subscribed"<subscribed@noreply.github.com&gt;;
主题: [Famine-Life/Lbook] 你好  (#1)



我下载 你的项目后 导入eclipse报错 可以给我指导一下吗

**Comment by zhaokailin** [comment]
能否给联系方式  ------------------ 原始邮件 ------------------
发件人: "练涛"<notifications@github.com>
发送时间: 2019年11月2日(星期六) 中午11:58
收件人: "Famine-Life/Lbook"<Lbook@noreply.github.com>;
抄送: "zhaokailin"<1669848435@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [Famine-Life/Lbook] 你好  (#1)


报错信息贴出来 
 
 
 
 ---原始邮&#x4EF6;--- 
 发&#x4EF6;人: "zhaokailin"<notifications@github.com&gt; 
 发送时间: 2019年11月2日(星期六) 中午11:50 
 收&#x4EF6;人: "Famine-Life/Lbook"<Lbook@noreply.github.com&gt;; 
 抄送: "Subscribed"<subscribed@noreply.github.com&gt;; 
 主题: [Famine-Life/Lbook] 你好  (#1) 
 
 
 
 我下载 你的项目后 导入eclipse报错 可以给我指导一下吗 
   
 — 
 You are receiving this because you are subscribed to this thread. 
 Reply to this email directly, view it on GitHub, or unsubscribe. 
&mdash;

**Comment by zhaokailin** [comment]
方便留个联系方式吗&nbsp;






------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"练涛"<notifications@github.com&gt;;
发送时间:&nbsp;2019年11月2日(星期六) 中午11:58
收件人:&nbsp;"Famine-Life/Lbook"<Lbook@noreply.github.com&gt;;
抄送:&nbsp;"奋斗///拼搏"<1669848435@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [Famine-Life/Lbook] 你好  (#1)



报错信息贴出来 
 
 
 
 ---原始邮件--- 
 发件人: "zhaokailin"<notifications@github.com&amp;gt; 
 发送时间: 2019年11月2日(星期六) 中午11:50 
 收件人: "Famine-Life/Lbook"<Lbook@noreply.github.com&amp;gt;; 
 抄送: "Subscribed"<subscribed@noreply.github.com&amp;gt;; 
 主题: [Famine-Life/Lbook] 你好  (#1) 
 
 
 
 我下载 你的项目后 导入eclipse报错 可以给我指导一下吗
